### ISSUE TITLE
Error while building first time

### ISSUE THREAD

**Issue by iegik** [airbnb/react-sketchapp#167]
**Observed behavior:**

```
$ npm run render
> basic-setup@1.0.0 render /Users/developer/Development/tools/react-sketchapp/examples/basic-setup
> skpm build --watch --run

🖨  Copied src/manifest.json in 5ms
error Error while building
TypeError: Cannot read property 'apply' of undefined
    at Compiler.apply (/Users/developer/Development/tools/react-sketchapp/examples/basic-setup/node_modules/tapable/lib/Tapable.js:375:15)
    at webpack (/Users/developer/Development/tools/react-sketchapp/examples/basic-setup/node_modules/webpack/lib/webpack.js:32:19)
    at /Users/developer/Development/tools/react-sketchapp/examples/basic-setup/node_modules/skpm/lib/skpm-build.js:209:24
    at Array.map (native)
    at /Users/developer/Development/tools/react-sketchapp/examples/basic-setup/node_modules/skpm/lib/skpm-build.js:207:50
    at <anonymous>
```

**How to reproduce:**

```
git clone https://github.com/airbnb/react-sketchapp.git
cd react-sketchapp/examples/basic-setup && npm install
npm run render
```

**Sketch version:**

41.2

**Comment by brianveltman** [comment]
As the readme specifies:
Quickstart 🏃‍
First, make sure you have installed **Sketch version 43+**, & a recent npm.
