### ISSUE TITLE
Faced a problem when I tried to run basic-setup in the quick-start on Ubuntu.

### ISSUE THREAD

**Issue by lambda-knight** [airbnb/react-sketchapp#212]
👋 Hello! Thanks for contributing. Please use the template that matches your intention  

_I am lambda-knight.
I faced a problem when I tried to run basic-setup in the quick-start on Ubuntu.

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**

 I expect npm i works fine in the examples/basic-setup directory.

**Observed behavior:**

In the examples/basic-setup directory, npm -i causes the following error:

```
$ npm i

> basic-setup@1.0.0 postinstall /home/makoto/js/react-sketchapp/examples/basic-setup
> npm run build && skpm-link


> basic-setup@1.0.0 build /home/makoto/js/react-sketchapp/examples/basic-setup
> skpm-build

[1/2] 🖨  Copied src/manifest.json in 12ms
[2/2] 🔧  Built ./my-command.js in 1000ms
success Plugin built
[1/1] 🔗  Symlinking the plugin basic-setup...
error Error while symlinking the plugin basic-setup
{ Error: ENOENT: no such file or directory, mkdir '/home/makoto/Library/Application Support/com.bohemiancoding.sketch3/Plugins/basic-setup'
    at Object.fs.mkdirSync (fs.js:892:18)
    at Object.<anonymous> (/home/makoto/js/react-sketchapp/examples/basic-setup/node_modules/@skpm/builder/lib/link.js:105:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/home/makoto/Library/Application Support/com.bohemiancoding.sketch3/Plugins/basic-setup' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! basic-setup@1.0.0 postinstall: `npm run build && skpm-link`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the basic-setup@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/makoto/.npm/_logs/2017-12-05T14_44_58_886Z-debug.log

```
**How to reproduce:**
On ubuntu 16.04, the following commands can reproduce the problem.
```
git clone https://github.com/airbnb/react-sketchapp.git
cd react-sketchapp/examples/basic-setup && npm install
```

**Sketch version:**

Latest commit fe8af15 

**Please attach screenshots, a zip file of your project, and/or a link to your github project**

https://github.com/airbnb/react-sketchapp

**Comment by mathieudutour** [comment]
You need Sketch to use this library and Sketch doesn't support Linux
