### ISSUE TITLE
Basic Setup example errors with: "Unknown command run"

### ISSUE THREAD

**Issue by BillyZac** [airbnb/react-sketchapp#31]
_I am..._

| -------------------------------------------------------------------------------------------------
| Reporting a bug or issue
| -------------------------------------------------------------------------------------------------

**Expected behavior:**
See the Basic Setup example running in Sketch & React.

**Observed behavior:**
See an error `Unknown command run` and and Webpack related error. Here's the terminal output:

```
> basic-setup@1.0.0 render /Users/zacharysmith/play/react-sketchapp/examples/basic-setup
> skpm build --watch --run

🖨  Copied src/manifest.json in 6ms
Executing post-build scripts
🔩  Built ./my-command.js in 1713ms
Unknown command ‘run’

Usage: sketchtool <command> [<args>]
                  [--formats=<string> | -f <string>]
                  [--use-id-for-name{=YES|NO} | --no-use-id-for-name | -n {<YES|NO>}]
                  [--max-size=<float> | -m <float>]
                  [--item=<string> | -i <string>]
                  [--items=<string> | -a <string>]
                  [--background=<string> | -g <string>]
                  [--compression=<float> | -c <float>]
                  [--reveal{=YES|NO} | --no-reveal | -r {<YES|NO>}]
                  [--outputJSON=<path> | -J <path>]
                  [--include-symbols{=YES|NO} | --no-include-symbols | - {<YES|NO>}]
                  [--bounds=<rectangle> | -b <rectangle>]
                  [--version | -v] [--filename=<string> | -F <string>]
                  [--scales=<path> | -s <path>]
                  [--compact{=YES|NO} | --no-compact | -k {<YES|NO>}]
                  [--overwriting{=YES|NO} | --no-overwriting | -V {<YES|NO>}]
                  [--trimmed{=YES|NO} | --no-trimmed | -t {<YES|NO>}]
                  [--group-contents-only{=YES|NO} | --no-group-contents-only | -G {<YES|NO>}]
                  [--help | -h]
                  [--include-namespaces{=YES|NO} | --no-include-namespaces | -N {<YES|NO>}]
                  [--progressive{=YES|NO} | --no-progressive | -p {<YES|NO>}]
                  [--save-for-web{=YES|NO} | --no-save-for-web | -w {<YES|NO>}]
                  [--output=<path> | -o <path>]

Commands:
	dump                 Dump out the structure of a document as JSON.

	export artboards     Export one or more artboards
	export layers        Export one or more layers
	export pages         Export an area from one or more pages
	export preview       Export a preview image for a document
	export slices        Export one or more slices

	help                 Show this help message.

	list artboards       List information on the document's artboards.
	list formats         List the supported export formats.
	list layers          List information on all of the document's layers.
	list pages           List information on the document's pages.
	list slices          List information on the document's slices.

	metadata             List the metadata for a document.
	notes                Output the release notes.
	show                 Show the location of the various sketch folders.


See ‘sketchtool help <command>’ for more information on a specific command.

/Users/zacharysmith/play/react-sketchapp/examples/basic-setup/node_modules/webpack-shell-plugin/lib/index.js:168
        throw error;
        ^
1

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/bin/npm" "run" "render"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! basic-setup@1.0.0 render: `skpm build --watch --run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the basic-setup@1.0.0 render script 'skpm build --watch --run'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the basic-setup package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     skpm build --watch --run
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs basic-setup
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls basic-setup
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zacharysmith/play/react-sketchapp/examples/basic-setup/npm-debug.log
```

**How to reproduce:**
Follow the instructions given in the `basic-setup`:
https://github.com/airbnb/react-sketchapp/tree/master/examples/basic-setup.

Specifically:

```
git clone https://github.com/airbnb/react-sketchapp.git
cd react-sketchapp/examples/basic-setup && npm install
npm run render
```

**Sketch version:**
42

**Please attach screenshots, a zip file of your project, and/or a link to your github project**

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.7.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'render' ]
2 info using npm@3.10.7
3 info using node@v6.7.0
4 verbose run-script [ 'prerender', 'render', 'postrender' ]
5 info lifecycle basic-setup@1.0.0~prerender: basic-setup@1.0.0
6 silly lifecycle basic-setup@1.0.0~prerender: no script for prerender, continuing
7 info lifecycle basic-setup@1.0.0~render: basic-setup@1.0.0
8 verbose lifecycle basic-setup@1.0.0~render: unsafe-perm in lifecycle true
9 verbose lifecycle basic-setup@1.0.0~render: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/zacharysmith/play/react-sketchapp/examples/basic-setup/node_modules/.bin:/usr/local/Cellar/node/6.7.0/bin:/Users/zacharysmith/.rvm/gems/ruby-2.3.0/bin:/Users/zacharysmith/.rvm/gems/ruby-2.3.0@global/bin:/Users/zacharysmith/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/zacharysmith/.rvm/bin
10 verbose lifecycle basic-setup@1.0.0~render: CWD: /Users/zacharysmith/play/react-sketchapp/examples/basic-setup
11 silly lifecycle basic-setup@1.0.0~render: Args: [ '-c', 'skpm build --watch --run' ]
12 silly lifecycle basic-setup@1.0.0~render: Returned: code: 1  signal: null
13 info lifecycle basic-setup@1.0.0~render: Failed to exec render script
14 verbose stack Error: basic-setup@1.0.0 render: `skpm build --watch --run`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid basic-setup@1.0.0
16 verbose cwd /Users/zacharysmith/play/react-sketchapp/examples/basic-setup
17 error Darwin 16.5.0
18 error argv "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/bin/npm" "run" "render"
19 error node v6.7.0
20 error npm  v3.10.7
21 error code ELIFECYCLE
22 error basic-setup@1.0.0 render: `skpm build --watch --run`
22 error Exit status 1
23 error Failed at the basic-setup@1.0.0 render script 'skpm build --watch --run'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the basic-setup package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     skpm build --watch --run
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs basic-setup
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls basic-setup
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by jongold** [comment]
Looks like you're running Sketch 42, not Sketch 43 — this project needs 43+ :(

Before you upgrade, be aware that files aren't backwards compatible, so please use your discretion if you share files with others!

**Comment by BillyZac** [comment]
Ah, that did it. Thank you!
