### ISSUE TITLE
cannot get the example to run

### ISSUE THREAD

**Issue by adamclark64** [airbnb/react-sketchapp#38]
**I am reporting a bug or issue**
cannot get the example to run

**Expected behavior:**
    app starts sketch 
**Observed behavior:**
  ```
  react-sketchapp/examples/basic-setup on master via ⬢ v7.7.1
➔ npm run render

> basic-setup@1.0.0 render /Users/adamclark/repos/react-sketchapp/examples/basic-setup
> skpm build --watch --run

🖨  Copied src/manifest.json in 9ms
Executing post-build scripts
⛏  Built ./my-command.js in 1407ms
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool ENOENT
    at exports._errnoException (util.js:1029:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! basic-setup@1.0.0 render: `skpm build --watch --run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the basic-setup@1.0.0 render script 'skpm build --watch --run'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the basic-setup package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     skpm build --watch --run
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs basic-setup
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls basic-setup
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

```
**How to reproduce:**
using sketch 43.2, node 7.7.1, and npm 4.5 
```
git clone https://github.com/airbnb/react-sketchapp.git
cd react-sketchapp/examples/basic-setup && npm install

npm run render
```
**Sketch version:**
sketch 43.2
**Please attach screenshots, a zip file of your project, and/or a link to your github project**
just trying to run the example

**Comment by jongold** [comment]
🤔 sounds like Sketch might be installed in a different location - can you try the solution in #27 and report back?

**Comment by adamclark64** [comment]
nice this looks promising. will let you know and thank you for the quick response!

**Comment by adamclark64** [comment]
the config was throwing js-yaml errors but moving sketch from /downloads to /applications was all it took 👌

**Comment by jongold** [comment]
ahah, that makes sense. perhaps skpm could check for the presence of sketchtool before trying to run it 🤔

**Comment by adamclark64** [comment]
🤔 and throw an error referencing location of sketch not being in /applications. not sure if that covers all the basis that error but for #27 and my issue it would've been a quick fix!
