### ISSUE TITLE
Not Building, Python Error

### ISSUE THREAD

**Issue by merlinpatt** [airbnb/react-sketchapp#406]
**Expected behavior:**
`npm install` is able to complete

**Observed behavior:**
On this step
```
> yoga-layout@1.9.3 copy-sources /Users/merlinpatterson/code/react-sketchapp/examples/basic-setup/node_modules/yoga-layout
> ! npm -s run is-monolithic || (rsync -r --checksum --delete ../yoga/ sources/yoga/)
```

I get the following error:
```
Error: Command failed: /Users/merlinpatterson/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
  File "<string>", line 1
    import sys; print "%s.%s.%s" % sys.version_info[:3];
                                ^
SyntaxError: invalid syntax
 
     at ChildProcess.exithandler (child_process.js:289:12)
     at ChildProcess.emit (events.js:182:13)
     at maybeClose (internal/child_process.js:962:16)
     at Socket.stream.socket.on (internal/child_process.js:381:11)
     at Socket.emit (events.js:182:13)
     at Pipe._handle.close (net.js:606:12)
```

**How to reproduce:**
Clone a fresh copy of react-sketchapp. Attempt `npm install`. Fails.

**Sketch version:** 50.2

**Please attach screenshots, a zip file of your project, and/or a link to your github project**
Fresh copy, so I don't think this is needed?

**Comment by mathieudutour** [comment]
fixed in v3
